### ISSUE TITLE
Internal Server error: /administration/smppccm/manage/

### ISSUE THREAD

**Issue by eloygn** [tarikogut/JasminWebPanel#15]
Hi,

SMPPCCM -> Menu "Add New SMPP Client Connector" doesn't work and Apache server returns the  following error:

[Sat Nov 03 16:43:13.112074 2018] [authz_core:debug] [pid 18719] mod_authz_core.c(809): [client IP_ADDRESS2:4406] AH01626: authorization result of Require all granted: gr
anted, referer: http://IP_ADDRESS/administration/smppccm/
[Sat Nov 03 16:43:13.112120 2018] [authz_core:debug] [pid 18719] mod_authz_core.c(809): [client IP_ADDRESS2:4406] AH01626: authorization result of <RequireAny>: granted, 
referer: http://IP_ADDRESS/administration/smppccm/
[Sat Nov 03 16:43:13.112181 2018] [authz_core:debug] [pid 18719] mod_authz_core.c(809): [client IP_ADDRESS2:4406] AH01626: authorization result of Require all granted: gr
anted, referer: http://IP_ADDRESS/administration/smppccm/
[Sat Nov 03 16:43:13.112186 2018] [authz_core:debug] [pid 18719] mod_authz_core.c(809): [client IP_ADDRESS2:4406] AH01626: authorization result of <RequireAny>: granted, 
referer: http://IP_ADDRESS/administration/smppccm/
**[Sat Nov 03 16:33:54.579753 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775] Internal Server Error: /administration/smppccm/manage/**
[Sat Nov 03 16:33:54.579846 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775] Traceback (most recent call last):
[Sat Nov 03 16:33:54.579852 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", l
ine 39, in inner
[Sat Nov 03 16:33:54.579854 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]     response = get_response(request)
[Sat Nov 03 16:33:54.579857 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 1
87, in _get_response
[Sat Nov 03 16:33:54.579860 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]     response = self.process_exception_by_middleware(e, request)
[Sat Nov 03 16:33:54.579862 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 1
85, in _get_response
[Sat Nov 03 16:33:54.579865 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sat Nov 03 16:33:54.579867 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", l
ine 23, in _wrapped_view
[Sat Nov 03 16:33:54.579870 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]     return view_func(request, *args, **kwargs)
[Sat Nov 03 16:33:54.579872 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]   File "/var/www/html/main/apps/administration/views/smppccm.py", line 25, in smppcc
m_view_manage
[Sat Nov 03 16:33:54.579875 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]     tc = TelnetConnection()
[Sat Nov 03 16:33:54.579877 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]   File "/var/www/html/main/apps/core/smpp/conn.py", line 13, in __init__
[Sat Nov 03 16:33:54.579879 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775]     raise TelnetUnexpectedResponse
[Sat Nov 03 16:33:54.579882 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775] TelnetUnexpectedResponse: Unexpected response from Jasmin
[Sat Nov 03 16:33:54.595988 2018] [wsgi:error] [pid 18644] [remote IP_ADDRESS2:40775] Exception AttributeError: AttributeError("'TelnetConnection' object has no attribute
 'telnet'",) in <bound method TelnetConnection.__del__ of <main.apps.core.smpp.conn.TelnetConnection object at 0x7f666ec69cd0>> ignored

I did a ubuntu installation following [https://jasmin.readthedocs.io/en/latest/installation/index.html] then pip install -r requirements.pip and all the stuff documented in README.md. Permissions for /var/www/html is 755

**Comment by brestows** [comment]
I have the same problem

**Comment by brestows** [comment]
check  option TELNET_HOSTin the config file asminWebPanel/main/ local_settings.py  
default:
TELNET_HOST = os.environ.get('JASMIN_HOST', 'jasmin')
my option:
TELNET_HOST = '127.0.0.1'
After that, everything will work

**Comment by eloygn** [comment]
Thanks brestows. That solves the issue!
