### ISSUE TITLE
Add another Indicator status (Session Status) for SMPP Connectors

### ISSUE THREAD

**Issue by amechax** [tarikogut/JasminWebPanel#2]
Status to show whether it is in bound state (Session BOUND_TRX) or not

smppccm -l
#Connector id                        Service Session          Starts Stops
#testroute                           started None             1      0    
#nextroute                           started None             1      0   

I suggest Orange color if session not bound

**Comment by tarek-aec** [comment]
We added session state in smppccm list 
thank you for suggestion
