### ISSUE TITLE
the 000-default.conf file is empty

### ISSUE THREAD

**Issue by jaimzj** [tarikogut/JasminWebPanel#8]
Hello Team,

I setup everything as instructed however, the 000-default.conf file is empty both on github and in the downloaded and installed script.

further, even the `./manage.py runserver` does not work for some reason although it shows that it has started running on `127.0.0.1:8000`

**Comment by tarek-aec** [comment]
You are right we will modify it now

**Comment by jaimzj** [comment]
@tarek-aec  thank you for the response, is that a bug? that `./manage.py runserver` also does not work?
I am trying to get this up and running, but unable to.

**Comment by tarek-aec** [comment]
Hello jaimzj have you installed `virtualenv` on your machine ?
it is important to install local env and then activate it e.g `source env/bin/activate` to use then you need to install `pip install -r requirements.pip`

**Comment by jaimzj** [comment]
I am very new to programming, i had missed out on the `virtualenv` , so now i have installed it. however now when i run

`./manage.py migrate` it returns me the following error, sorry for the huge chunk of error log copied here.

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_li          ne
    utility.execute()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 63, in           execute
    return super(Command, self).execute(*args, **options)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/ubuntu/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/jasmin/web/main/urls.py", line 26, in <module>
    from main.apps.core.views import (
  File "/opt/jasmin/web/main/apps/core/views/__init__.py", line 2, in <module>
    from .users import UserViewSet
  File "/opt/jasmin/web/main/apps/core/views/users.py", line 8, in <module>
    from main.apps.core.tools import set_ikeys
  File "/opt/jasmin/web/main/apps/core/tools.py", line 13
    print key, val
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by tarek-aec** [comment]
Yes it is print "Hello Python2.7" it is python2 not python3 you should distinct between, in this project we are using 

> Python2.7

 not Python3, 
So when you create new virtualenv `virtualenv -p python2 env` to create virtualenv that runs python2 please be care about, and happy new year :)

**Comment by jaimzj** [comment]
A very happy new year to you too :)

Thanks for the support, I really wanted to get this webpanel up and running :) I am going to try with the command you shared above for python 2.7 and return here..

**Comment by tarek-aec** [comment]
You're welcome, I will be happy to help

**Comment by jaimzj** [comment]
Hello Tarek,

I tried everything installed without any errors, including i used virtualenv. and I run the app for testing option. and it shows this on command line. however when i access the ip and port 

http://142.44.245.1:8000/

it does not work,

`System check identified no issues (0 silenced).
January 01, 2018 - 02:04:13
Django version 1.10.5, using settings 'main.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.


browser returns this error 

This site can’t be reached
142.44.245.1 refused to connect.
Search Google for 142 245 8000
ERR_CONNECTION_REFUSED

`

**Comment by tarek-aec** [comment]
Hi,
When you want to run on server for test you need write `python manage.py runserver 0.0.0.0:8000` then you can reach it on browser.

**Comment by jaimzj** [comment]
Hey @tarek-aec 

Finally got it up and running, :) But my lack of expertise and knowledge in python and scripting has got me stuck again.

This time the interface works, but whenever I add soemthing from the UI it does not save.

And when in CLI i add it does not reflect here. (Sharing screenshot) will require your guidance again...

**Comment by jaimzj** [comment]
I also configured apache conf file as shared, the page loads this way. and unable to login either.


![image](https://user-images.githubusercontent.com/1138485/34469569-1a2cbbee-eef0-11e7-940e-55f6b2e2e1c9.png)

**Comment by tarek-aec** [comment]
you need to make collectstatic to your code on server 
in project directory `python manage.py collectstatic` this command will move all assets (css, js, img, ..etc) to directory that defined in apache configuration file.

**Comment by jaimzj** [comment]
Both the collectstatic has been run and Jasmin Gateway is installed.

**Comment by tarek-aec** [comment]
I think you need to change configuration of static in 000-default.conf, where you located project, the static folder should be seen in Alias /static, as I see in screenshot you have set project in /opt/jasmin/web
you need to change it as `Alias /static /opt/jasmin/web/static/`.

**Comment by jaimzj** [comment]
`<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /opt/jasmin/web
        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
        <Directory /opt/jasmin/web>
                <Files django.wsgi>
                        Require all granted
                </Files>
        </Directory>
        WSGIDaemonProcess html python-path=/opt/jasmin/web:/home/ubuntu/jweb/local/lib/python2.7/site-packages
        WSGIProcessGroup html
        WSGIScriptAlias / /opt/jasmin/web/django.wsgi
        Alias /static /opt/jasmin/web/static/
</VirtualHost>`

the above is my 000-default.conf file, even still i get the following situation. (screenshot below) and when i submit a credential on this page, it gives 500 error.

I am sure something I have done wrong, for sure.


![image](https://user-images.githubusercontent.com/1138485/34470005-c6e4ff62-eef6-11e7-8073-188ce435b2e8.png)

**Comment by tarek-aec** [comment]
it is missing installation, credential error because you need install database e.g. PostgreSQL or MySQL, you could not run project on Sqlite3 as production, so you need to install and add new database then make 
`python manage.py syncdb` or `python manage.py migrate` then add new superuser like `python manage.py createsuperuser`, 
for static file I think it is permission missing make sure to set /static folder owned by `www-data` by `sudo chown www-data: -R /static` and also `sudo chmod -R 755 /static` to make it enabled to public.
I have simple tutorial for django getting started deployment 
https://gist.github.com/tarek-aec/074ebbe9e02ab1df6a7f
also simple tutorial for django development
https://gist.github.com/tarek-aec/a3afec3e138345cc4170

**Comment by jaimzj** [comment]
Thank you once again, got the database mysql up and running and tables generated etc. the tutorials were helpful in achieving it.

I think this will be the last question as I have already given permissions to /static folder as suggested b you and still the pages load with login.css and login.js not working.

I came across this file, please advice if this is correct? django.wsgi 

below is the content of it,  all my jasminwebpanel files are under

/opt/jasmin/web

```
import os
import sys
import site

site.addsitedir('/var/www/html/env/lib/python2.7/site-packages')

sys.path.append('/var/www/html')
sys.path.append('/var/www/html/main')

os.environ['PYTHON_EGG_CACHE'] = '/var/www/html/egg_cache'
os.environ['DJANGO_SETTINGS_MODULE'] = 'main.settings'

# for Django <= 1.6
# import django.core.handlers.wsgi
# application = django.core.handlers.wsgi.WSGIHandler()

# for Django 1.8 and 1.7
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```

and 000-default.conf files part is like this

```
WSGIDaemonProcess html python-path=/opt/jasmin/web:/home/ubuntu/jweb/local/lib/python2.7/site-packages
        WSGIProcessGroup html
        WSGIScriptAlias / /opt/jasmin/web/django.wsgi
        Alias /static /opt/jasmin/web/static/
```

Still trying to figure out why it does give Forbidden error. when permissions are also created rightly.

**Comment by tarek-aec** [comment]
Hi Jaimz,

as you see I configured all project to be under /var/www/html folder as apache2 default directory, you have set all project in /opt/jasmin/web, and it should no matter but you need to configure files such as `django.wsgi` , `000-default.conf`, etc ... I prefer set project under /var/www/html or you will need configure files in this project to run as wsgi app under apache2.
OR, in current situation you need configure the previeus files as you located in your machine, please be careful about it.
So, static/ folder there so many reasons could be happen, have you got static/ folder empty as root directory /opt/jasmin/web/static/, it could be persmission files in folder and you should specify `www-data` privileged to let apache2 access this folder as owner on server. If something wrong, you could contact me by Hangout to solve this issue.

**Comment by sizzlephizzle** [comment]
Hi @tarek-aec , I have followed through these comments trying to resolve my own issue but sadly, this has not resolved.
I can runserver on 8000 but my static is also failing. I have CHOWN and CHMOD for www-data but still no joy. 
I'm using /var/www/html.
Debug currently set to False
I can login fine and navigate through menu's. There is a mysql server on the machine.
I also copied static to /var/www/html manually but this failed to work.
![image](https://user-images.githubusercontent.com/36083373/37207905-0a615388-2397-11e8-9f50-038f8ea23b99.png)
I have mysql installed but not postgres.
I also have no idea about using virtualenv, so I built this within screen -t webUI

Summary: 8000 works without static
sudo service apache2 restart doesn't produce anything at all.

I'd welcome any advice.

**Comment by tarek-aec** [comment]
Hi Sizzle,

you need to learn more about django web framework command line
I have quick tutorial [here](https://gist.github.com/tarek-aec/a3afec3e138345cc4170)
you need to create virtualenv in project location, please do not copy static files manually I you did you need to change permission and change owner to 'www-data' user as Apache2 server's user.
```
user@host$ cd /var/www/html
user@host$ pwd
/var/www/html
user@host$ sudo apt-get install python-setuptools git python-pip && sudo easy_install virtualenv
user@host$ virtualenv env
user@host$ source env/bin/activate
(env)user@host$ pip install -r requirements.pip
...
(env)user@host$ python manage.py migrate
...
(env)user@host$ python manage.py createsuperuser
....
(env)user@host$ python manage.py collectstatic
(env)user@host$
```
Then try to do deployment in [link](https://github.com/tarikogut/JasminWebPanel/#deployment)

I hope this help you.

**Comment by sizzlephizzle** [comment]
Thanks @tarek-aec - working on it now. as you go from env/bin/active to pip install -r requirements.pip, does this mean the JasminWebPanel files should be extracted to /var/www/html as this is the pwd?

**Comment by tarek-aec** [comment]
Hi,
`/var/www/html` it is recommended as I write 000-default.conf for apache2 server, if you changed the folder location you need to configure it.

**Comment by sizzlephizzle** [comment]
I'm using default server settings, so sticking with var/html to make it easier (hopefully). Reading the django doc now.

**Comment by tarek-aec** [comment]
Hi,
It seems pip libraries not installed when you have virtualenv active  You need to do once `pip install -r requirements.pip`
If you still got issue contact me on `Hangouts` by gmail
